#!/bin/bash
echo "Testing Blink UI..."
echo ""
echo "1. UI Form endpoint:"
curl -s http://localhost:8080/ui | grep -o "<title>.*</title>"
echo ""
echo "2. Starting browser test..."
echo "   Open http://localhost:8080/ui in your browser"
echo ""
echo "3. Test URLs to try:"
echo "   - Fast: https://google.com"
echo "   - With redirects: http://github.com"
echo "   - Error: https://invalid.fake"
echo ""
